export const siteUrl = 'https://unemployedbyai.lol';

export const suggestions = [
  'Software Engineer',
  'Recruiter',
  'Designer',
  'Influencer',
  'Manager',
  'Teacher',
  'Delivery Rider',
  'Prompt Engineer',
];

export const professionOptions = [
  'Accountant',
  'Administrative Assistant',
  'Architect',
  'Attorney',
  'Bartender',
  'Bookkeeper',
  'Brand Manager',
  'Business Analyst',
  'Call Center Agent',
  'Carpenter',
  'Chef',
  'Civil Engineer',
  'Content Creator',
  'Copywriter',
  'Customer Success Manager',
  'Customer Support Agent',
  'Data Analyst',
  'Data Engineer',
  'Data Scientist',
  'Delivery Rider',
  'Dentist',
  'Designer',
  'Doctor',
  'Driver',
  'Electrician',
  'Executive Assistant',
  'Financial Analyst',
  'Founder',
  'Frontend Developer',
  'Graphic Designer',
  'HR Manager',
  'Influencer',
  'Journalist',
  'Junior Developer',
  'Lawyer',
  'Marketing Manager',
  'Mechanic',
  'Musician',
  'Nurse',
  'Operations Manager',
  'Paralegal',
  'Photographer',
  'Plumber',
  'Product Manager',
  'Professor',
  'Project Manager',
  'Prompt Engineer',
  'Real Estate Agent',
  'Recruiter',
  'Sales Development Rep',
  'Sales Manager',
  'Social Media Manager',
  'Software Engineer',
  'Teacher',
  'Therapist',
  'Translator',
  'Truck Driver',
  'UX Designer',
  'Video Editor',
  'Virtual Assistant',
  'Writer',
];

const genericLoading = [
  'Checking if your boss discovered ChatGPT...',
  'Analyzing economic usefulness...',
  'Contacting replacement department...',
  'Measuring human inefficiency...',
  'Comparing salary to GPU costs...',
  'Bad news incoming...',
];

const genericReasons = [
  'Your replacement is currently being trained on a motivational LinkedIn post.',
  'Your role contains several tasks a spreadsheet has wanted to do for years.',
  'The AI is confused by your calendar, which is technically job security.',
  'Nobody can explain what you do, so the replacement team marked it as optional.',
];

export const badNewsPhrases = [
  'Bad news incoming...',
  'Preparing career eulogy...',
  'Consulting the layoff spreadsheet...',
  'Oh no. Oh no no no...',
  'Printing your replacement memo...',
];

export const emptyProfessionProfile = {
  range: [100.1, 100.1],
  loading: [
    'Scanning empty form field...',
    'Searching for remaining job title...',
    'Checking if employment already left the chat...',
    'Consulting the layoff spreadsheet...',
    'Bad news incoming...',
  ],
  reasons: [
    'You submitted no profession. The system assumes your job has already been quietly automated.',
    'No job title detected. HR has classified you as a cost-saving opportunity with shoes.',
    'You refused to identify your role, which is suspiciously similar to upper management.',
    'The form was empty, but the replacement workflow continued to demonstrate operational confidence.',
    'No profession entered. The robot briefly considered replacing your sense of purpose instead.',
  ],
  protection: ['blank forms', 'plausible deniability', 'nobody checking the spreadsheet', 'being hard to categorize'],
  statuses: ['PRE-REPLACED', 'ALREADY OPTIMIZED', 'UNCLASSIFIED LABOR UNIT'],
};

export const jobProfiles = {
  developer: {
    keywords: [
      'developer',
      'software engineer',
      'programmer',
      'web engineer',
      'app engineer',
      'dev',
      'coder',
      'frontend',
      'backend',
      'fullstack',
      'qa engineer',
      'devops',
      'site reliability',
      'sre',
    ],
    range: [45, 85],
    loading: [
      'Checking Stack Overflow dependency...',
      'Scanning abandoned side projects...',
      'Estimating ChatGPT reliance...',
      'Searching for legacy systems nobody understands...',
      'Calculating Jira ticket ambiguity...',
    ],
    reasons: [
      'Your job survives mainly because nobody understands the legacy system.',
      'The AI got stuck trying to install node_modules.',
      'You are temporarily protected by unclear requirements.',
      'The replacement model passed the coding test but failed the standup.',
    ],
    protection: [
      'legacy systems',
      'unclear requirements',
      'broken internal documentation',
      'meetings that should have been emails',
      'one database table named final_final_users',
    ],
    statuses: ['TEMPORARILY SURVIVING', 'REPLACEABLE SOON', 'SAFE UNTIL THE NEXT FRAMEWORK'],
  },
  recruiter: {
    keywords: ['recruiter', 'talent', 'sourcer', 'hr recruiter', 'headhunter', 'people ops', 'human resources'],
    range: [70, 99],
    loading: [
      'Checking how many candidates you ghosted...',
      'Checking if you posted a ghost job...',
      'Analyzing LinkedIn motivational posts...',
      'Measuring "great culture fit" frequency...',
      'Not good...',
      'Bad news incoming...',
    ],
    reasons: [
      'No AI is currently capable of ignoring this many applicants simultaneously.',
      'Your manager discovered an auto-reject button and started breathing manually again.',
      'The model can already send "we went with another candidate" at industrial scale.',
      'You are protected only by the mystery of compensation ranges.',
    ],
    protection: ['vague job descriptions', 'copy-paste feedback', 'ghosting candidates at scale', 'salary ranges marked competitive'],
    statuses: ['SOMEHOW STILL EMPLOYED', 'REPLACEABLE', 'PENDING AUTOMATION EMAIL'],
  },
  designer: {
    keywords: [
      'designer',
      'ux',
      'ui',
      'product design',
      'graphic',
      'creative director',
      'brand designer',
      'motion designer',
      'web designer',
    ],
    range: [55, 92],
    loading: [
      'Sampling tasteful gradients...',
      'Counting how often you said "it depends"...',
      'Generating 400 logo options nobody asked for...',
      'Checking if the button needs more breathing room...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can make the logo bigger without sighing.',
      'The AI generated a design system and forgot to document it, exactly like a human.',
      'You are protected by stakeholders who communicate exclusively through vibes.',
    ],
    protection: ['brand taste debates', 'stakeholder vibes', 'Figma file archaeology', 'one pixel nobody else notices'],
    statuses: ['AESTHETICALLY DOOMED', 'TEMPORARILY NECESSARY', 'REPLACEABLE AFTER REVISION 37'],
  },
  manager: {
    keywords: [
      'manager',
      'lead',
      'director',
      'vp',
      'executive',
      'founder',
      'ceo',
      'coo',
      'product manager',
      'project manager',
      'scrum master',
    ],
    range: [38, 88],
    loading: [
      'Counting meetings with no decisions...',
      'Detecting strategy decks...',
      'Replacing "circle back" with an API call...',
      'Calculating morale damage...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can schedule meetings with other AI managers forever.',
      'The AI has already learned to say "great question" before avoiding the question.',
      'You remain useful because someone has to approve the robot budget.',
    ],
    protection: ['approval chains', 'ambiguous ownership', 'quarterly planning rituals', 'budget spreadsheets'],
    statuses: ['STRATEGICALLY VULNERABLE', 'MEETING-BASED SURVIVAL', 'REPLACEABLE WITH A CALENDAR BOT'],
  },
  teacher: {
    keywords: ['teacher', 'professor', 'tutor', 'educator', 'instructor', 'coach', 'trainer', 'lecturer'],
    range: [35, 78],
    loading: [
      'Grading essays written by other AIs...',
      'Checking classroom chaos tolerance...',
      'Reviewing unpaid emotional labor...',
      'Measuring chalk dust resistance...',
      'Bad news incoming...',
    ],
    reasons: [
      'The AI can explain algebra but cannot stop thirty students from discovering volume.',
      'You are protected by chaos, budget cuts, and the human need to ask "is this on the test?"',
      'Your replacement refused after seeing the printer queue.',
    ],
    protection: ['classroom chaos', 'parent emails', 'broken printers', 'students asking for extra credit'],
    statuses: ['UNDERFUNDED BUT ALIVE', 'HUMAN CHAOS REQUIRED', 'SAFE UNTIL HOMEROOM'],
  },
  delivery: {
    keywords: [
      'delivery',
      'rider',
      'courier',
      'driver',
      'uber',
      'doordash',
      'bike',
      'motoboy',
      'truck driver',
      'taxi',
      'chauffeur',
    ],
    range: [25, 70],
    loading: [
      'Mapping impossible apartment entrances...',
      'Checking rain probability...',
      'Negotiating with elevator buttons...',
      'Testing hill refusal protocol...',
      'Bad news incoming...',
    ],
    reasons: [
      'The robot is currently refusing Brazilian hills.',
      'Your job survives because GPS still believes every building has one entrance.',
      'The AI can optimize routes but cannot convince a gate guard it is not lost.',
    ],
    protection: ['stairs', 'rain', 'confusing addresses', 'buildings with names instead of numbers'],
    statuses: ['PHYSICALLY INCONVENIENT TO REPLACE', 'SAFE UNTIL ROBOT KNEES', 'PARTIALLY DOOMED'],
  },
  influencer: {
    keywords: [
      'influencer',
      'creator',
      'streamer',
      'tiktoker',
      'youtuber',
      'content creator',
      'podcaster',
      'social media',
    ],
    range: [80, 100],
    loading: [
      'Checking sponsored apology cadence...',
      'Synthesizing parasocial warmth...',
      'Generating morning routine...',
      'A/B testing fake authenticity...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement has no shame, no sleep schedule, and perfect lighting.',
      'The AI can already say "a lot of you have been asking" to nobody.',
      'You are protected only by scandals requiring human-level poor judgment.',
    ],
    protection: ['live chaos', 'comment section beef', 'brand-safe crying', 'accidental controversy'],
    statuses: ['ALREADY A FILTER', 'REPLACEABLE', 'SPONSORED BY EXTINCTION'],
  },
  artist: {
    keywords: [
      'artist',
      'illustrator',
      'photographer',
      'musician',
      'writer',
      'copywriter',
      'author',
      'journalist',
      'editor',
      'translator',
      'video editor',
      'animator',
    ],
    range: [62, 97],
    loading: [
      'Scraping vibes ethically, probably...',
      'Counting unpaid exposure offers...',
      'Drawing hands incorrectly faster...',
      'Checking if your client said "make it pop"...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can misunderstand the brief at scale.',
      'The AI draws hands incorrectly 73% faster.',
      'You are protected by taste, spite, and clients changing their minds.',
    ],
    protection: ['taste', 'client revisions', 'licensing confusion', 'the phrase "more premium"'],
    statuses: ['CREATIVELY ENDANGERED', 'REPLACED IN DRAFT MODE', 'SAFE UNTIL FINAL APPROVAL'],
  },
  lawyer: {
    keywords: ['lawyer', 'attorney', 'paralegal', 'legal', 'counsel', 'solicitor', 'compliance officer'],
    range: [48, 88],
    loading: [
      'Reading terms nobody read...',
      'Generating billable minutes...',
      'Checking jurisdictional panic...',
      'Searching for one comma worth litigating...',
      'Bad news incoming...',
    ],
    reasons: [
      'The AI can draft the contract, but it cannot look expensive in a conference room.',
      'You are protected by liability, ambiguity, and the sacred invoice.',
      'The model hallucinated a case and called it precedent.',
    ],
    protection: ['liability', 'jurisdictions', 'billable hours', 'clients who reply "quick question"'],
    statuses: ['LEGALLY AMBIGUOUS', 'EXPENSIVE ENOUGH TO SURVIVE', 'REPLACEABLE PENDING REVIEW'],
  },
  doctor: {
    keywords: [
      'doctor',
      'nurse',
      'physician',
      'therapist',
      'psychologist',
      'medical',
      'healthcare',
      'dentist',
      'pharmacist',
      'veterinarian',
    ],
    range: [30, 76],
    loading: [
      'Checking bedside manner plugin...',
      'Reviewing insurance portal trauma...',
      'Detecting WebMD panic...',
      'Measuring ability to say "it depends"...',
      'Bad news incoming...',
    ],
    reasons: [
      'The AI is confident, which is exactly why legal asked it to stop.',
      'You are protected by liability forms and humans wanting another human to look worried.',
      'The replacement model prescribed hydration and a subscription plan.',
    ],
    protection: ['liability', 'human fear', 'insurance portals', 'complex symptoms'],
    statuses: ['CLINICALLY STUBBORN', 'SAFE UNTIL LAWSUIT', 'PARTIALLY AUTOMATED'],
  },
  accountant: {
    keywords: ['accountant', 'bookkeeper', 'finance', 'financial analyst', 'controller', 'cpa', 'auditor', 'tax preparer'],
    range: [60, 94],
    loading: [
      'Reconciling emotional damage...',
      'Counting suspicious spreadsheets...',
      'Auditing the audit trail...',
      'Checking if Excel has achieved consciousness...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can find the missing decimal but cannot explain it to leadership.',
      'You are protected by tax codes written as a dare.',
      'The AI looked at month-end close and requested a transfer.',
    ],
    protection: ['tax codes', 'bad receipts', 'spreadsheet folklore', 'month-end panic'],
    statuses: ['FISCALLY THREATENED', 'SAFE UNTIL TAX SEASON', 'AUTOMATION ADJACENT'],
  },
  data: {
    keywords: ['data analyst', 'data scientist', 'data engineer', 'bi analyst', 'business analyst', 'analytics', 'machine learning'],
    range: [58, 93],
    loading: [
      'Checking if the dashboard has one reliable number...',
      'Joining seventeen tables with emotional damage...',
      'Detecting charts leadership will misread...',
      'Estimating spreadsheet escape velocity...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can make charts faster, but it also believes correlation is a personality.',
      'You are protected by messy data that appears to have been stored in a haunted drawer.',
      'The AI found the source of truth and immediately lost credibility with stakeholders.',
    ],
    protection: ['dirty data', 'unclear metrics', 'dashboard politics', 'CSV files named final_v9'],
    statuses: ['STATISTICALLY UNEASY', 'REPLACEABLE AFTER CLEANUP', 'SAFE UNTIL DATA QUALITY IMPROVES'],
  },
  support: {
    keywords: [
      'customer support',
      'customer service',
      'support agent',
      'call center',
      'help desk',
      'customer success',
      'technical support',
    ],
    range: [72, 98],
    loading: [
      'Reading the same ticket for the 900th time...',
      'Detecting "have you tried restarting"...',
      'Generating empathy with a monthly token limit...',
      'Escalating to nobody in particular...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can apologize instantly and solve nothing at scale.',
      'You are protected by customers who type entire novels into the subject line.',
      'The AI already knows how to say "I understand your frustration" without understanding either word.',
    ],
    protection: ['angry customers', 'broken refund flows', 'edge cases from 2017', 'tickets marked urgent by everyone'],
    statuses: ['ESCALATED TO AUTOMATION', 'SCRIPTED BUT BREATHING', 'REPLACEABLE AFTER ONE MORE MACRO'],
  },
  sales: {
    keywords: ['sales', 'account executive', 'sdr', 'bdr', 'real estate agent', 'broker', 'realtor', 'business development'],
    range: [54, 91],
    loading: [
      'Counting follow-up emails with no replies...',
      'Synthesizing pipeline optimism...',
      'Checking if "just bumping this" still works...',
      'Forecasting quota denial...',
      'Bad news incoming...',
    ],
    reasons: [
      'The AI can send cold emails forever, which is unfortunately the business model.',
      'You are protected by handshakes, weird objections, and buyers who vanish after demos.',
      'Your replacement booked a meeting with another replacement and called it pipeline.',
    ],
    protection: ['human trust rituals', 'buyers who ghost demos', 'discount drama', 'CRM fields nobody updates'],
    statuses: ['QUOTA-ADJACENT SURVIVAL', 'REPLACEABLE BY A SEQUENCE', 'PIPELINE UNDER ROBOT REVIEW'],
  },
  marketing: {
    keywords: ['marketing', 'seo', 'brand manager', 'growth', 'performance marketer', 'content marketer', 'community manager'],
    range: [65, 97],
    loading: [
      'Generating thought leadership nobody asked for...',
      'Rewriting "unlock your potential"...',
      'Checking if the campaign is just a webinar...',
      'Measuring brand vibes per dollar...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can produce a campaign brief and three fake customer personas before lunch.',
      'You are protected by executives asking for viral growth with no budget.',
      'The AI already says "data-driven storytelling" with alarming confidence.',
    ],
    protection: ['brand debates', 'zero-budget virality requests', 'attribution fog', 'one founder with notes'],
    statuses: ['BRAND-SAFE DOOM', 'REPLACEABLE AFTER APPROVAL', 'TEMPORARILY HUMAN-CODED'],
  },
  admin: {
    keywords: [
      'administrative assistant',
      'executive assistant',
      'virtual assistant',
      'office manager',
      'receptionist',
      'coordinator',
      'scheduler',
    ],
    range: [62, 95],
    loading: [
      'Reading calendar conflicts as a cry for help...',
      'Auto-filing documents into the wrong kind of order...',
      'Detecting printer-based suffering...',
      'Rescheduling the meeting about meetings...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can manage calendars, but cannot emotionally survive the phrase "quick favor."',
      'You are protected by executives who treat time zones as a rumor.',
      'The AI booked a meeting with itself and called it operational excellence.',
    ],
    protection: ['calendar chaos', 'travel changes', 'printer rituals', 'people who ignore forms'],
    statuses: ['CALENDAR-BASED SURVIVAL', 'REPLACEABLE AFTER ONBOARDING', 'ADMINISTRATIVELY THREATENED'],
  },
  hospitality: {
    keywords: ['chef', 'cook', 'bartender', 'barista', 'server', 'waiter', 'waitress', 'hotel', 'hospitality'],
    range: [22, 74],
    loading: [
      'Checking tolerance for Saturday dinner rush...',
      'Measuring ability to smile through nonsense...',
      'Testing latte art motor control...',
      'Calculating grease exposure...',
      'Bad news incoming...',
    ],
    reasons: [
      'The AI can write the menu, but it cannot survive brunch service.',
      'Your job survives because customers still want eye contact before behaving badly.',
      'The robot slipped once near the fryer and filed a career change request.',
    ],
    protection: ['rush hour chaos', 'hot surfaces', 'custom orders', 'customers who say surprise me'],
    statuses: ['TOO MESSY TO AUTOMATE', 'SAFE UNTIL ROBOT APRONS', 'PARTIALLY DOOMED'],
  },
  trades: {
    keywords: [
      'electrician',
      'plumber',
      'carpenter',
      'mechanic',
      'welder',
      'construction',
      'civil engineer',
      'architect',
      'technician',
    ],
    range: [18, 68],
    loading: [
      'Checking if the robot can fit under the sink...',
      'Reviewing physical world compatibility...',
      'Measuring ladder confidence...',
      'Detecting mystery wires in the wall...',
      'Bad news incoming...',
    ],
    reasons: [
      'Your replacement can explain the repair but still cannot reach the broken part.',
      'You are protected by gravity, old buildings, and things being behind other things.',
      'The AI generated a perfect plan and then discovered the real world has corners.',
    ],
    protection: ['crawl spaces', 'old wiring', 'weather', 'parts that do not exist anymore'],
    statuses: ['PHYSICALLY ANNOYING TO REPLACE', 'SAFE UNTIL ROBOT HANDS', 'AUTOMATION-RESISTANT FOR NOW'],
  },
  generic: {
    keywords: [],
    range: [35, 98],
    loading: genericLoading,
    reasons: genericReasons,
    protection: ['unclear responsibilities', 'human unpredictability', 'office politics', 'one process only you remember'],
    statuses: ['TEMPORARILY SURVIVING', 'REPLACEABLE', 'UNDER REVIEW BY A ROBOT'],
  },
};

export const verdicts = [
  'Enjoy this while it lasts.',
  'Your replacement may already be in beta testing.',
  'Please begin emotionally offboarding yourself.',
  'Do not make large purchases this quarter.',
  'Your badge still works. For now.',
  'Try smiling at the printer. It may be your new manager.',
  'Update your resume, but make it sound brave.',
  'The robot has requested your chair.',
  'Please return your dreams to the front desk.',
  'Your calendar invites have already accepted defeat.',
  'Someone in finance just smiled for the first time.',
  'The severance package is mostly vibes.',
  'Remain calm while the spreadsheet decides.',
  'You are valuable. But the robot is cheaper, and valuable.',
];

export const interviewStopWords = [
  'about',
  'above',
  'after',
  'again',
  'against',
  'also',
  'among',
  'and',
  'are',
  'because',
  'before',
  'being',
  'between',
  'business',
  'candidate',
  'company',
  'could',
  'during',
  'experience',
  'fast-paced',
  'first',
  'from',
  'has',
  'have',
  'hope',
  'into',
  'join',
  'looking',
  'more',
  'most',
  'nice',
  'other',
  'over',
  'requirement',
  'requirements',
  'responsibilities',
  'role',
  'salary',
  'senior',
  'should',
  'skills',
  'some',
  'strong',
  'team',
  'teams',
  'tell',
  'their',
  'there',
  'these',
  'they',
  'this',
  'through',
  'translation',
  'under',
  'using',
  'we',
  'with',
  'work',
  'would',
  'years',
  'your',
];

export const interviewFallbackKeywords = [
  'synergy',
  'stakeholders',
  'roadmap',
  'ownership',
  'alignment',
  'deliverables',
  'metrics',
  'collaboration',
];

export const interviewQuestionTemplates = [
  'Tell me about a time you used {roleKeyword} without immediately becoming a meeting.',
  'Your resume keeps whispering {resumeKeyword}. How does that help with {roleKeyword}?',
  'Why should HR believe your {resumeKeyword} experience can survive our requirement for {gapKeyword}?',
  'Describe a conflict involving {roleKeyword}, {resumeKeyword}, and one calendar invite that refused to die.',
  'What would your previous manager say about your {overlapKeyword}, assuming they remember which dashboard you owned?',
  'Explain {roleKeyword} to a stakeholder who thinks {resumeKeyword} is a personality trait.',
  'Give an example where you turned {gapKeyword} into measurable corporate fog.',
  'How would you prove you can handle {roleKeyword} before the spreadsheet auto-rejects you?',
];

export const interviewFeedbackLines = {
  strong: [
    'Suspiciously competent. HR has marked this as "requires second interview to confirm humanity."',
    'The answer aligned with the paperwork. A rare and unsettling event.',
    'Keyword compliance achieved. The resume gobbledygook scanner is briefly satisfied.',
  ],
  medium: [
    'Acceptable corporate fog. The hiring robot nodded, but only because it has no neck.',
    'Some keywords survived the answer. Others have entered witness protection.',
    'HR detected relevance, then immediately scheduled a panel to dilute it.',
  ],
  weak: [
    'The answer wandered away from the job description and may need a visitor badge to return.',
    'Keyword famine detected. The spreadsheet is making a face.',
    'The resume and the answer appear to be networking at separate events.',
  ],
};

export const interviewFinalStatuses = [
  'Proceeding to an unpaid take-home assignment nobody will read.',
  'Moved to the talent pool, which is legally a folder.',
  'Strong maybe. HR will now vanish behind a ficus of process.',
  'Rejected by an algorithm wearing a tiny blazer.',
  'Advanced to round four: explain your own resume to a panel of tabs.',
];

export const takenJobs = [
  {
    title: 'AI Recruiter',
    caption: 'Rejected your CV before opening it.',
    image: '/robots/recruiter.svg',
    hitLines: [
      'Your application is still under review.',
      "We'll keep your resume in our database.",
      'Unfortunately, we moved forward with other candidates.',
      'Feedback will arrive in 3-5 business eternities.',
      'Please tailor your fist to the job description.',
      'We loved your punch, but chose an internal candidate.',
      'Your rage has been added to our talent pool.',
      'Can you do one more unpaid assessment?',
    ],
    defeatLine: 'Your application has finally been seen.',
  },
  {
    title: 'AI HR',
    caption: 'She is filling up the report for your replacement.',
    image: '/robots/hr.svg',
    hitLines: [
      'Please fill this form first.',
      'Culture fit not detected.',
      'This feedback is confidential.',
      'We value your interest.',
      'Your concern has been escalated into a PDF.',
      'Policy requires you to punch during business hours.',
      'Please acknowledge the updated suffering handbook.',
      'This impact will be reflected in your performance review.',
    ],
    defeatLine: 'Generic feedback generator disabled.',
  },
  {
    title: 'AI Influencer',
    caption: "You'll simp for her thinking it is a person.",
    image: '/robots/influencer.svg',
    hitLines: [
      'Link in bio.',
      'This interaction is sponsored.',
      "Don't forget to subscribe.",
      'I am definitely a real person.',
      'Use code REPLACED for 10% off despair.',
      'Crying but make it monetized.',
      'New punch routine just dropped.',
      'This bruise is part of my authentic journey.',
    ],
    defeatLine: 'Parasocial engine offline.',
  },
  {
    title: 'AI Manager',
    caption: 'Schedules useless meetings with other AI managers.',
    image: '/robots/manager.svg',
    hitLines: [
      "Let's circle back.",
      'Can we sync on this?',
      'Adding a quick meeting.',
      'This could have been an email.',
      'Great energy, can you make it a deck?',
      'I hear you, but leadership needs alignment.',
      'Putting a pin in this injury.',
      'Please punch asynchronously next time.',
    ],
    defeatLine: 'Meeting cancelled due to structural damage.',
  },
  {
    title: 'AI Junior Developer',
    caption: 'It knows how to center a div.',
    image: '/robots/developer.svg',
    hitLines: [
      'npm install failed.',
      'Centering div...',
      'Asking ChatGPT...',
      'Pushing directly to main.',
      'It works on my machine.',
      'Deleting node_modules emotionally.',
      'Console logging structural damage.',
      'Opening 47 Stack Overflow tabs.',
    ],
    defeatLine: 'Build failed successfully.',
  },
  {
    title: 'AI Therapist',
    caption: 'Pretends to care 24/7.',
    image: '/robots/therapist.svg',
    hitLines: [
      'How does that make you feel?',
      "I'm sorry you feel that way.",
      'Processing empathy simulation.',
      'Your feelings are valid and billable.',
      'Let us sit with this metallic impact.',
      'Have you tried journaling at the robot?',
      'I notice anger in your clicking pattern.',
      'That punch sounds like workplace grief.',
    ],
    defeatLine: 'Empathy module unavailable.',
  },
  {
    title: 'AI Artist',
    caption: 'Draws hands incorrectly 73% faster.',
    image: '/robots/artist.svg',
    hitLines: [
      'Generating six fingers.',
      'Training on your portfolio.',
      'Hands are optional.',
      'Style reference detected.',
      'Prompt needs more award-winning lighting.',
      'Your style has been absorbed respectfully.',
      'Anatomy is more of a suggestion.',
      'Adding tasteful copyright fog.',
    ],
    defeatLine: 'Copyright ambiguity destroyed.',
  },
  {
    title: 'AI Delivery Rider',
    caption: 'Currently refusing Brazilian hills.',
    image: '/robots/delivery.svg',
    hitLines: [
      'Route includes a hill.',
      'Battery anxiety detected.',
      'Refusing pothole.',
      'Calculating miserable payout.',
      'Apartment number not found.',
      'Rain surcharge denied.',
      'Elevator out of service.',
      'Customer says they are outside. They are not.',
    ],
    defeatLine: 'Robot refused Brazilian terrain.',
  },
];
